kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: task-bloom
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30007
        hostPort: 30007
        protocol: TCP
      - containerPort: 30008
        hostPort: 30008
        protocol: TCP
